version: '3'
services:
  db:
    build: .
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
      - nc_data:/usr/app/data
      - ./db:/usr/app/backup
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
  nocodb:
      image: nocodb/nocodb:0.84.10
      restart: always
      depends_on:
        - db
          # condition: service_healthy
      ports:
        - "8080:8080"
      environment:
        NC_DB: "pg://db:5432?user=$POSTGRES_USER&p=$POSTGRES_PASSWORD&d=$POSTGRES_DB"
volumes:
  db_data:
  nc_data: